### ISSUE TITLE
Improve Form Validation

### ISSUE THREAD

**Issue by Deafveloper** [Deafveloper/verify-the-job#2]
Add client-side validation to the form to ensure users enter valid input before submission.

Tasks:

- [x] Implement checks to ensure that the “company” and “description” fields are not empty.
- [x] Add error messages for invalid or missing inputs.
- [x] Enhance user experience by providing inline validation feedback.

**Comment by LucasFeli** [comment]
Hello, can I solve this issue?

**Comment by Deafveloper** [comment]
Hello, Yes, please.

**Comment by LucasFeli** [comment]
let me know if everything is ok
